services:
  turtle-backend:
    build:
      target: development
    ports:
      - "${PORT}:${PORT}"
    networks:
      - backend_network
    environment:
      PORT: ${PORT}
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      postgres-db:
        condition: service_healthy
    develop:
      watch:
        - path: ./src
          action: sync
          target: /usr/src/app/src
        - action: rebuild
          path: package.json
  postgres-db:
    image: postgres:18-alpine
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "pg_isready", "-d", "${POSTGRES_DB}", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGUSER: ${POSTGRES_USER}
      PGPASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${HOST_POSTGRES_PORT}:5432
    volumes:
      - pg-data:/var/lib/postgresql/18/docker
      - ./database/scripts/initialization:/docker-entrypoint-initdb.d
    deploy:
      resources:
        limits:
          memory: 512m
        reservations:
          memory: 256m
    networks:
      - backend_network
      - dba_network
  pgadmin:
    image: dpage/pgadmin4:9.14.0
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-O", "-", "http://localhost:80/misc/ping"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
    profiles:
      - dbClient
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - ${HOST_PGADMIN_PORT}:80
    volumes:
      - pg-admin-data:/var/lib/pgadmin
    deploy:
      resources:
        limits:
          memory: 256m
        reservations:
          memory: 128m
    networks:
      - dba_network